<?php

namespace App\Repositories\Articles;

use App\Model\ArticleCategory;
use App\Repositories\EloquentRepository;

class ArticleCategoryRepository extends EloquentRepository
{

    protected $Articles;//文章

    public function __construct(ArticleCategory $model, ArticlesRepository $Articles)
    {
        parent::__construct($model);
        $this->Articles = $Articles;
    }


    public function delete($id)
    {

        //分类下如果有文章禁止删除此分类
        $article = $this->Articles->findBy('category_id', $id, ['id'])->toArray();

        if (!empty($article)) {
            return back()->withErrors('此分类下有文章，无法删除');
        }
        //分类下如果有子分类禁止删除此分类
        $childCategory = parent::findBy('pid', $id, ['id'])->toArray();
        if (!empty($childCategory)) {
            return back()->withErrors('此分类下有子分类，无法删除');
        }
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}