<?php

namespace App\Repositories\AdminUser;

use App\Model\UserGroup;
use App\Model\UserRelationalGroup;
use App\Repositories\EloquentRepository;

class UserGroupRepository extends EloquentRepository
{

    protected $UserRelationalGroup;

    public function __construct(UserGroup $model, UserRelationalGroup $UserRelationalGroup)
    {
        parent::__construct($model);
        $this->UserRelationalGroup = $UserRelationalGroup;
    }

    public function delete($id)
    {
        //查询该用户组中是否有用户
        $user = $this->UserRelationalGroup->where('gid', '=', $id)->exists();
        if ($user == true) {
            return back()->withErrors('此用户组下面有用户，无法删除');
        }
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}